# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2023-10-16 15:43:47
"""
import arcpy

def Model():  # Model

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    # Check out any necessary licenses.
    arcpy.CheckOutExtension("BusinessPrem")
    arcpy.CheckOutExtension("Business")
    arcpy.CheckOutExtension("Foundation")
    arcpy.CheckOutExtension("Defense")

    arcpy.ImportToolbox(r"c:\program files\arcgis\pro\Resources\ArcToolbox\toolboxes\Data Management Tools.tbx")
    Instance_Vector = "C:\\Users\\Lauren\\Desktop\\composites_probas_2_wMed_2\\shapes\\pred3702_bnd0pt2_ext0pt3.shp"

    # Process: Identify Narrow Polygons (Identify Narrow Polygons) (topographic)
    Name = "pred3702_bnd0pt2_ext0pt3"
    narrow_identified = fr"C:\Users\Lauren\AppData\Local\Temp\ArcGISProTemp26216\{Name}_1Narro.shp"
    arcpy.topographic.IdentifyNarrowPolygons(in_features=Instance_Vector, out_feature_class=narrow_identified, min_width="15 Meters", min_length="15 Meters")

    # Process: Add Field (Add Field) (management)
    split_fields_w_area_column = arcpy.management.AddField(in_table=narrow_identified, field_name="area", field_type="DOUBLE")[0]

    # Process: Calculate Geometry Attributes (Calculate Geometry Attributes) (management)
    split_fields_w_area_populated = arcpy.management.CalculateGeometryAttributes(in_features=split_fields_w_area_column, geometry_property=[["area", "AREA"]], area_unit="SQUARE_METERS", coordinate_system="PROJCS[\"WGS 84 / Equal Earth Americas\",GEOGCS[\"WGS 84\",DATUM[\"World Geodetic System 1984\",SPHEROID[\"WGS 84\",6378137.0,298.257223563]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Equal_Earth\"],PARAMETER[\"False easting\",0.0],PARAMETER[\"False northing\",0.0],PARAMETER[\"Longitude of natural origin\",-90.0],UNIT[\"metre\",1.0]]")[0]

    # Process: Select (Select) (analysis)
    non_sliver_split_fields = fr"C:\Users\Lauren\Documents\ArcGIS\Projects\MyProject\MyProject.gdb\{Name}_2area"
    arcpy.analysis.Select(in_features=split_fields_w_area_populated, out_feature_class=non_sliver_split_fields, where_clause="area > 100")

    # Process: Pairwise Dissolve (Pairwise Dissolve) (analysis)
    dissolved_split_fields = fr"C:\Users\Lauren\Documents\ArcGIS\Projects\MyProject\MyProject.gdb\{Name}_3PairwiseDisso"
    arcpy.analysis.PairwiseDissolve(in_features=non_sliver_split_fields, out_feature_class=dissolved_split_fields)

    # Process: Select Layer By Location (Select Layer By Location) (management)
    missing_fields_from_Identify_Narrow_step, Output_Layer_Names, Count = arcpy.management.SelectLayerByLocation(in_layer=[Instance_Vector], overlap_type="SHARE_A_LINE_SEGMENT_WITH", select_features=dissolved_split_fields, invert_spatial_relationship="INVERT")

    # Process: Merge (Merge) (management)
    ALL_split_fields = fr"C:\Users\Lauren\Documents\ArcGIS\Projects\MyProject\MyProject.gdb\{Name}_4Merge"
    arcpy.management.Merge(inputs=[dissolved_split_fields, missing_fields_from_Identify_Narrow_step], output=ALL_split_fields, field_mappings="Shape_Length \"Shape_Length\" false true true 8 Double 0 0,First,#,C:\\Users\\Lauren\\Documents\\ArcGIS\\Projects\\MyProject\\.\\MyProject.gdb\\pred_PY1000ch__PairwiseDisso,Shape_Length,-1,-1;Shape_Area \"Shape_Area\" false true true 8 Double 0 0,First,#,C:\\Users\\Lauren\\Documents\\ArcGIS\\Projects\\MyProject\\.\\MyProject.gdb\\pred_PY1000ch__PairwiseDisso,Shape_Area,-1,-1;raster_val \"raster_val\" true true false 19 Double 0 0,First,#,pred3702_bnd0pt2_ext0pt3_Lay1,raster_val,-1,-1")

    # Process: Eliminate Polygon Part (Eliminate Polygon Part) (management)
    holes_removed = fr"C:\Users\Lauren\Documents\ArcGIS\Projects\MyProject\MyProject.gdb\{Name}_5rmHoles"
    arcpy.management.EliminatePolygonPart(in_features=ALL_split_fields, out_feature_class=holes_removed, condition="PERCENT", part_area_percent=5)

    # Process: Buffer (Buffer) (analysis)
    increase_lost_crop_area_from_border_mask = fr"C:\Users\Lauren\Documents\ArcGIS\Projects\MyProject\MyProject.gdb\{Name}_6Buf"
    arcpy.analysis.Buffer(in_features=holes_removed, out_feature_class=increase_lost_crop_area_from_border_mask, buffer_distance_or_field="10 Meters", line_end_type="FLAT")

    # Process: Remove Overlap (multiple) (Remove Overlap (multiple)) (ba)
    remove_overlapping_area_of_fields = fr"C:\Users\Lauren\Documents\ArcGIS\Projects\MyProject\MyProject.gdb\{Name}_7rmOlap"
    arcpy.ba.RemoveOverlapMultiple(in_features=[increase_lost_crop_area_from_border_mask], out_feature_class=remove_overlapping_area_of_fields, method="GRID")

    # Process: Export Features (Export Features) (conversion)
    out_fields = fr"C:\Users\Lauren\Desktop\composites_probas_2_wMed_2\shapes\edited\{Name}_instance.shp"
    arcpy.conversion.ExportFeatures(in_features=remove_overlapping_area_of_fields, out_features=out_fields)

    # Process: Parse Path (Parse Path) (mb)
    Path, Name, Extension, Workspace_Name = arcpy.mb.ParsePathExt(in_data_element=Instance_Vector)

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace="C:\\Users\\Lauren\\Documents\\ArcGIS\\Projects\\MyProject\\MyProject.gdb", workspace="C:\\Users\\Lauren\\Documents\\ArcGIS\\Projects\\MyProject\\MyProject.gdb"):
        Model()
